test_task:
  container:
    image: golang:latest
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get ./...
  build_script: go build ./...
  test_script: go test ./...
  smoke_script: go run . -h

lint_task:
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run

# release_task:
#   container:
#     image: goreleaser/goreleaser:latest
#   only_if: $CIRRUS_TAG != '' # run only on tags
#   depends_on:
#     - test
#     - lint
#     # any other sanity tasks
#   env:
#     GITHUB_TOKEN: ENCRYPTED[ABC]
#   release_script: goreleaser
